---
- name: Configure host
  hosts: letsencrypt
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt repo 
      apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
    
    - name: create cache directory
      file:
        path: /usr/share/nginx/cache/fcgi
        state: directory

  roles:
    - wordpress
    - geerlingguy.php
    - geerlingguy.nginx
    - role: geerlingguy.mysql
      become: yes
      tags: [db]
    - role: geerlingguy.certbot
      tags: [cert]


  tasks:
    - name: create info.php
      shell: |
        echo "<?php phpinfo(); ?>" >> /var/www/html/info.php

    - name: change php.ini file
      template:
        src: templates/wp_php.ini.j2
        dest: /etc/php/8.1/fpm/php.ini
