---
- name: Configure host
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt repo 
      apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day

  roles:
    - geerlingguy.php
    - geerlingguy.nginx
    - role: geerlingguy.mysql
      become: yes
    - wordpress

  tasks:
    - name: create info.php
      shell: |
        echo "<?php phpinfo(); ?>" >> /var/www/html/info.php
    
